### PR TITLE
WEB-76 Add user.addSubscription to support API changes

### PR DESCRIPTION
**Pull request by jazzywhit**
## Goals

Add user.addSubscription to support changes to API: https://github.com/tablelist/api/pull/687

## Results

Check all that apply to this pull request

- New Feature

## Checklist

Check off all items in this list before asking for a code review:

- [x] I added code documentation to any new services or methods

### CODE REVIEW

**Comment by jazzywhit** [comment]
Should be merged after https://github.com/tablelist/api/pull/687

**Comment by jazzywhit** [comment]
@alexjohnson505 is this what you needed?

**Comment by jazzywhit** [comment]
@alexjohnson505 Double check this; didn't realize this was still hanging around.

**Comment by alexjohnson505** [comment]
Incremented version, and added build folder. Looks good! 👍

**Pull request merged**
